### ISSUE TITLE
consider version in line zero

### ISSUE THREAD

**Issue by rjbs** [fastmail/mint-tag#4]
https://github.com/fastmail/mint-tag/blob/429607872c6986289dfac28133ffb2e89a6043c3/lib/App/MintTag.pm#L213-L217

This is fine, but I will restate my original advice, which are you free to discount, and I will not be bothered. :)

I said "be sure to put the version as the very first thing" which might be, say:

```
v19 tag from tag-minter where blah blah

[[...]]
pie = eaten
```

…because you'd always be able to parse that no matter what.  "Every tag starts with v then a string of digits, then a space."  You seem to have put it into the TOML, meaning that for all time, every tag is described in TOML.

Probably this is fine, and I just want to know you decided knowing what I had meant!

**Comment by mmcclimon** [comment]
I think it's fine. Because if we can't parse the tag annotation _anyway_, we'll just ignore it. That is: the only thing the previous annotations are used for is giving better human output in interactive mode. If later, we say "oh actually we should be in JSON", we'd already have to write code to handle both, or to ignore old-style tag formats (which we already do).
